# Generated by Django 4.1.1 on 2022-09-27 03:31

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=30, validators=[users.models.validate_email]),
        ),
    ]
