# Generated by Django 4.1.1 on 2022-09-27 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
