# Generated by Django 4.1.1 on 2022-09-26 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
